### PR TITLE
Updates the Regex pattern do identify dates

### PR DESCRIPTION
**Pull request by otavio-s-s**
Changed the Regex pattern to make the comma between the date and the time optional.

Also, I used the `re.split` function to split the date and the time since it allows two different separators. This is important so it can be properly split either with or without the comma.

### CODE REVIEW

**Comment by pcsingh** [comment]
Hi @otavio-s-s 

Thanks for showing your interest in this project 👏 . 

Please, open an issue [here](https://github.com/pcsingh/WhatsApp-Chat-Analyzer/issues/new) on which bug or feature you are working on. I will see your contribution and inform you.

**Comment by pcsingh** [comment]
@otavio-s-s  did you check on your local system after making these changes. Please take a look at the split part of `dateTime` string.

**Comment by otavio-s-s** [comment]
I did, yes. It's working fine:

**Comment by pcsingh** [comment]
Yes, the `|` in split will create a problem, if the time is not in 24-hour format. Such as "14/03/19, 9:05 am".

**Comment by otavio-s-s** [comment]
Oh, gotcha! I think the best solution would then be to use the normal `split` and then use `replace` to remove the comma from the date.

**Comment by pcsingh** [comment]
What I think is if there is no comma then add there and let the previous split do his job (split using `, `).

**Comment by otavio-s-s** [comment]
But hey, the time is the 24-hour format in both English and Portuguese versions, isn't it?

**Comment by pcsingh** [comment]
Not necessary, In my area time is not in 24-hour format 😄 .

**Comment by otavio-s-s** [comment]
Oh, ok! I thought with some standard pattern form WhatsApp, I'm sorry. How would you suggest checking for the comma?

**Comment by pcsingh** [comment]
I think, leave the split part as it is and add code if there is no comma in `dateTime` then replace first space with this `, `.

**Comment by otavio-s-s** [comment]
Done!

**Comment by pcsingh** [comment]
Congratulations @otavio-s-s 🎉 on your contribution to WhatsApp Chat Analyzer. Soon you will see its effect on the app.

**Pull request merged**
