### PR TITLE
Different date formats added

### PR DESCRIPTION
**Pull request by otavio-s-s**
The app now uses different date formats for different types of .txt files.

Date formats available:

* mm/dd/yyyy

* dd/mm/yyyy

### CODE REVIEW

**Comment by pcsingh** [comment]
@otavio-s-s , check that chat text file with the app.


[check.txt](https://github.com/pcsingh/WhatsApp-Chat-Analyzer/files/5030460/check.txt)

**Comment by otavio-s-s** [comment]
Is this a real file? Does is it makes sense to expect date formats with a 2-digit year?

**Comment by pcsingh** [comment]
Yes, that's the real file but in short. 2-digit year format is in real chat file. When you try this it will give you a `ValueError`. This is the format of WhatsApp chat in India. I think these formats differ country wise.

**Comment by otavio-s-s** [comment]
Ok, no problem. Just added the solution for that. Your file is working fine now:

Capturar4

**Comment by pcsingh** [comment]
@otavio-s-s , according to the changes you made. There is one test case is left what if the date portion in `dateTime` (with comma) is "13/05/19".

**Comment by pcsingh** [comment]
I think you got it what I am saying.

**Comment by otavio-s-s** [comment]
I'm under the assumption that dates in files with comma are in already in the English format mm/dd/yy

**Comment by pcsingh** [comment]
But that's not the case, the file I have given to you is the real test case of it. The date on it is in the "%d/%m/%y" format.

**Comment by pcsingh** [comment]
I got its general solution but don't know how effective it is. We can use `infer_datetime_format` as `True` parameter in pd.to_datetime().

**Comment by otavio-s-s** [comment]
> But that's not the case, the file I have given to you is the real test case of it. The date on it is in the "%d/%m/%y" format.

Ok, but this file does not work in current version either. The difference in my suggestion is that at least %d/%m/%y" format without the comma would work.


> I got its general solution but don't know how effective it is. We can use `infer_datetime_format` as `True` parameter in pd.to_datetime().

I tried it, but it is not effective.

To cover every possible data format, I think the best solution is to create a drop-down list from where the user can select the date format.

**Comment by pcsingh** [comment]
@otavio-s-s , Can you give some cases where it fails?

**Comment by otavio-s-s** [comment]
Yes, that's your file on the current app. If the date in the file is in the "%d/%m/%y" format, then the app displays it wrong as it should be May, 12.

Capturar5

**Comment by pcsingh** [comment]
Yes
So the last option is drop-down list.

**Comment by pcsingh** [comment]
Would you like to work on it?

**Comment by otavio-s-s** [comment]
Yes, I'm almost done with it.

**Comment by otavio-s-s** [comment]
I'll create a new pull request.

**Pull request closed without merging**
